-- Procedures
CREATE OR REPLACE PROCEDURE AddDeliveryMethod(ID VARCHAR2, Name VARCHAR2)
AS
BEGIN
  INSERT INTO DELIVERY_METHODS (DELIVERY_METHOD_ID, DELIVERY_METHOD)
    VALUES (ID, Name);
END;

CREATE OR REPLACE PROCEDURE DeleteDeliveryMethod(ID VARCHAR2)
AS
BEGIN
  DELETE FROM DELIVERY_METHODS 
  WHERE DELIVERY_METHOD_ID = ID;
END;

--View compilation errors
SHOW ERRORS;